name: 'EKG'
description: 'fake ekg check action'
inputs:
  product:
    description: 'The product name'
    required: true    
  target_tuples:
    description: 'The (fabric_name, tag) string tuples of the targets'
    required: true
  criteria: 
    description: 'Criteria to succeed'
    required: true
  baseline_tag:
    description: 'Baseline tag'
    required: false
    default: 'DEFAULT'
  analysis_type:
    description: 'Analysis type'
    required: false
    default: 'any'
outputs:
  time:
    description: 'The time it uses'
  status: 
    description: 'Status of result'
runs:
  using: 'node12'
  main: 'ekg.js'
