name: 'EKG'
description: 'fake ekg check action'
inputs:
  criteria: 
    description: 'Criteria to succeed'
    required: true
  allowed_tags:
    description: 'Tags allowed'
    required: false
    default: 'DEFAULT'
  baseline_tag:
    description: 'Baseline tag'
    required: false
    default: 'DEFAULT'
  analysis_type:
    description: 'Analysis type'
    required: false
    default: 'any'
outputs:
  time:
    description: 'The time it uses'
  status: 
    description: 'Status of result'
runs:
  using: 'node12'
  main: 'ekg.js'
