name: 'Health Check'
description: 'fake health check action'
inputs:
  condition: 
    description: 'Condition to be met'
    required: true
    default: 'any'
  passing_status:
    description: 'Passing status'
    required: true
    default: 'DEFAULT'
  fabric_names:
    description: 'fabrics to take this action on'
    required: true
  tags:
    description: 'tags to take this action on'
    required: true
outputs:
  time:
    description: 'The time it uses'
  status: 
    description: 'Status of result'
runs:
  using: 'node12'
  main: 'healthcheck.js'
