name: 'Health Check'
description: 'fake health check action'
inputs:
  product:
    description: 'The product name'
    required: true
  condition: 
    description: 'Condition to be met'
    required: true
  passing_status:
    description: 'Passing status'
    required: true
  target_tuples:
    description: 'The (fabric_name, tag) string tuples of the targets'
    required: true
outputs:
  time:
    description: 'The time it uses'
  status: 
    description: 'Status of result'
runs:
  using: 'node12'
  main: 'healthcheck.js'
