name: 'Private Moratorium'
description: 'fake auto private moratorium'
inputs:
  product:
    description: 'duration to pause in mins'
    required: true
  target_tuples:
    description: 'The (fabric_name, tag) string tuples of the targets'
    required: true
  duration: 
    description: 'duration to pause in mins'
    required: true
  reason:
    description: 'reason for auto pause'
    required: true
outputs:
  time:
    description: 'The time it uses'
  status: 
    description: 'Status of result'
runs:
  using: 'node12'
  main: 'private_moratorium.js'
