name: 'Regression'
description: 'fake regression action'
inputs:
  condition: 
    description: 'Condition to be met'
    required: true
    default: 'any'
  passing_status:
    description: 'Passing status'
    required: true
    default: 'DEFAULT'
  target_tuples:
    description: 'The (fabric_name, tag) string tuples of the targets'
    required: true
outputs:
  time:
    description: 'The time it uses'
  status: 
    description: 'Status of result'
runs:
  using: 'node12'
  main: 'regression.js'
