name: default-with-triggers-and-signals

on: [push]

jobs:

  deploy_on_lit:
    runs-on: ubuntu-latest
    env:
      fabrics: (lit-lca1-1)    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: LIT_WITH_HEALTH_CHECK
      env:
        allowed_tags: lit-lca1-1.tag 
      run: echo deploying on $fabrics of tag $allowed_tags.
    - name: healthcheck on lit
      uses: ./actions/health-check/
      with:
        condition: all
        passing_status: SUCCEEDED 
        fabric_names: $fabrics
        tags: $allowed_tags
  
  deploy_on_ei:
    runs-on: ubuntu-latest
    env:
      fabrics: (ei-ltx1, ei4)
      
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: EI_WITH_ROLLBACK_ON_REGRESSION
      env:
        allowed_tags: (ei-ltx1.tag, ei-ltx4.tag)      
      run: echo deploying on $fabrics of tag $allowed_tags.
    - name: regression on ei
      uses: ./actions/regression/
      with:
        condition: all
        passing_status: SUCCEEDED
    - name: rollback on ei
      if: failure()
      uses: ./actions/trigger-a-workflow-job/
      with: 
        job_id: job-used-to-rollback                                              # Needs a definition of 'rollback' here
  
  deploy_on_corp:
    needs: [deploy_on_ei, deploy_on_lit]
    runs-on: ubuntu-latest
    env:
      fabrics: (corp-lca1, corp-ltx1, corp-lva1)   
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: CANARY_ON_CORP
      env:
        allowed_tags: (ei.canary.tag)      
      run: echo canarying on $fabrics of tag $allowed_tags.
    - name: ekg on corp
      uses: ./actions/ekg/
      with:
        criteria: all
        allowed_tags: (prod.canary.tag)
        baseline_tag: some_baseline_tag
        analysis_type: some_analysis_type
    - name: CANARY_PROMOTION_ON_CORP
      env:
        allowed_tags: (corp.tag) 
      run: echo deploying on $fabrics of tag $allowed_tags.
 
  deploy_on_prod:
    needs: deploy_on_corp
    runs-on: ubuntu-latest
    env:
      fabrics: (prod-lca1, prod-ltx1, prod-lva1, prod-lsg1)
      
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: PROD_WITH_ROLLBACK_ON_FAILED_REGRESSION
      env:
        allowed_tags: (prod.tag)      
      run: echo deploying on $fabrics of tag $allowed_tags.
    - name: regression on prod
      uses: ./actions/regression/regression         # incorrect path
      with:
        condition: all
        passing_status: SUCCEEDED
    - name: rollback on prod
      if: failure()
      uses: ./actions/trigger-a-workflow-job/
      with: 
        job_id: job-used-to-rollback-in-prod
    
