name: default-no-canaries

on: [push]

env:
  global_env: var                                                            # global env vars e.g. code_version

jobs:
  deploy_on_ei:
    runs-on: ubuntu-latest
    env:
      fabrics: (ei-ltx1, ei4)                                                    # yaml supports the value as arrays of string
      applications: (sample-applications)
      
    steps:
    - name: EI
      env:
        allowed_tags: (ei-ltx1.tag, ei-ltx4.tag)      
      run: echo deploying on $fabrics of tag $allowed_tags.

  deploy_on_lit:
    runs-on: ubuntu-latest
    env:
      fabrics: (lit-lca1-1)    
    steps:
    - name: LIT
      env:
        allowed_tags: lit-lca1-1.tag 
      run: echo deploying on $fabrics of tag $allowed_tags.
  
  deploy_on_corp:
    needs: [deploy_on_ei, deploy_on_lit]
    runs-on: ubuntu-latest
    env:
      fabrics: (corp-lca1, corp-ltx1, corp-lva1)   
    steps:
    - name: CORP_SHADOW
      env:
        allowed_tags: (corp_shadow.tag) 
      run: echo deploying on $fabrics of tag $allowed_tags.
    - name: CORP
      env:
        allowed_tags: (corp.tag) 
      run: echo deploying on $fabrics of tag $allowed_tags.

  deploy_on_prod:
    needs: deploy_on_corp
    runs-on: ubuntu-latest
    env:
      fabrics: (prod-lca1, prod-lva1. prod-lsg1, prod-ltx1)
    steps:
    - name: PROD
      env:
        allowed_tags: (prod.tag) 
      run: echo deploying on $fabrics of tag $allowed_tags.
    
