name: no-canaries

on: [push]

jobs:
  canary_and_promotion_on_ei:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      # auto-advance: true                                        --> toggle of auto-advance between steps
    env:
      fabrics: (ei-ltx1, ei4)                                     # yaml supports the value as array of strings

    steps:
    - name: CANARY
      env:
        allowed_tags: (ei.canary.tag)      
      run: echo canarying on $fabrics of tag $allowed_tags.
    - name: CANARY_PROMOTION_WITH_AUTO_PAUSE
      # schedule:                                                --> auto pause for duration of 15 mins
      #   - cron:  '*/15 * * * *'
      env:
        allowed_tags: (ei-ltx1.canary.tag, ei-ltx4.canary.tag)
        auto_pause_reason: auto_pause_15_mins
      run: echo promoting on $fabrics of tag $allowed_tags with $auto_pause_reason.
  
  canary_and_promotion_on_corp:
    needs: canary_and_promotion_on_ei
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      # auto-retry: true                                        --> toggle of auto-retry for steps in this job
    env:
      fabrics: (corp-lca1, corp-ltx1, corp-lva1)   
    steps:
    - name: CANARY_WITH_AUTO_RETRY
      env:
        allowed_tags: (corp.canary.tag)
        success_instance_number: 1
      run: echo deploying on $fabrics of tag $allowed_tags with success_instance_number $success_instance_number.
    - name: CANARY_PROMOTION_WITH_AUTO_RETRY
      env:
        allowed_tags: (corp.tag)
        success_rate: 0.75
        run: echo deploying on $fabrics of tag $allowed_tags with success_rate $success_rate.

  canary_and_promotion_on_prod:
    needs: canary_and_promotion_on_corp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      # ekg-configuration: true                                        --> toggle of ekg-configuration for steps in this job
    env:
      fabrics: (prod-lca1, prod-lva1. prod-lsg1, prod-ltx1)
    steps:
    - name: CANARY_WITH_EKG_CONFIGURATION
      env:
        allowed_tags: (prod.canary.tag)
        baseline_tag: some_baseline_tag
        analysis_type: some_analysis_type
      run: echo deploying on $fabrics of tag $allowed_tags with baseline_tag $baseline_tag and analysis_type $analysis_type.
    - name: CANARY_PROMOTION_WITH_EKG_CONFIGURATION
      env:
        allowed_tags: (prod.tag)
        run: echo deploying on $fabrics of tag $allowed_tags.
