name: default-with-triggers-and-signals

on: [push]

jobs:

  deploy_on_lit:
    runs-on: ubuntu-latest
    env:
      fabrics: (lit-lca1-1)    
    steps:
    - name: LIT_WITH_HEALTH_CHECK
      env:
        allowed_tags: lit-lca1-1.tag 
      run: echo deploying on $fabrics of tag $allowed_tags.
    - name: healthcheck on lit
      uses: ./actions/health-check/@master
      with:
        condition: all
        passing_status: SUCCEEDED 
        fabric_names: $fabrics
        tags: $allowed_tags
  
  deploy_on_ei:
    runs-on: ubuntu-latest
    env:
      fabrics: (ei-ltx1, ei4)
      
    steps:
    - name: EI_WITH_ROLLBACK_ON_FAILED_REGRESSION
      env:
        allowed_tags: (ei-ltx1.tag, ei-ltx4.tag)      
      run: echo deploying on $fabrics of tag $allowed_tags.
    - name: regression on ei
      uses: ./actions/regression/@master
      with:
        condition: all
        passing_status: SUCCEEDED
    - name: rollback on ei
      if: failure()
      uses: ./actions/trigger-a-workflow-job/@master
      with: 
        job_id: job-used-to-rollback                                              # Needs a definition of 'rollback' here
  
  deploy_on_corp:
    needs: [deploy_on_ei, deploy_on_lit]
    runs-on: ubuntu-latest
    env:
      fabrics: (corp-lca1, corp-ltx1, corp-lva1)   
    steps:
    - name: CANARY_ON_CORP
      env:
        allowed_tags: (ei.canary.tag)      
      run: echo canarying on $fabrics of tag $allowed_tags.
    - name: ekg on corp
      uses: ./actions/ekg/@master
      with:
        condition: all
        passing_status: SUCCEEDED
    - name: CANARY_PROMOTION_ON_CORP
      env:
        allowed_tags: (corp.tag) 
      run: echo deploying on $fabrics of tag $allowed_tags.
    
