# Workflow diagram:
#   ei-ltx1   -->|                  corp                        prod
#                |      -->   shadow ->  deploy     -->  canary  -> promotion
#   ei4       -->|  
name: default-lid-deployabale    # This is the GHA version of lid_deployable default workflow

on: [push]                      # This workflow is triggered by a success postcommit

env:
  code_version: code_version                                                # Global arguements taken from either user inputs or the event who triggered this workflow
  config_version: config_version
  auto_retry: true                                                          # toggle of auto-retry strategy in this job 

jobs:                                                                       
  deploy_on_ei-ltx1:
    runs-on: ubuntu-latest
    env:
      auto_retry_success_rate: 0.8                                          
       
    steps:
    - name: Checkout                                                        # This is only for passing building GHA. We do not need checkout before taking actions in our w/f.
      uses: actions/checkout@master                                          
    - name: deploy_on_ei_ltx1
      run: echo ${{ toJson(github.workflow) }} and ${{ toJson(job) }}
#       uses: ./actions/deploy_targets/                            
#       with: 
#         target_tuples: (ei-ltx1, None)
#         code_version: ${{ toJson(workflow) }}
#         config_version: ${{ toJson(job) }}
#         auto_retry: ${auto_retry}
#         auto_retry_success_rate: ${deploy_on_ei-ltx1.env.auto_retry_success_rate}

  deploy_on_ei4:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: deploy_on_ei4
      uses: ./actions/deploy_targets/                            
      with: 
        target_tuples: (ei4, None)
        code_version: ${{env.code_version}}
        config_version: ${{env.config_version}}
        auto_retry: ${{env.auto_retry}}
  
  deploy_on_corp:
    needs: [deploy_on_ei-ltx1, deploy_on_ei4]                                               
    runs-on: ubuntu-latest
    env:
      auto_retry_success_rate: 0.8 
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: shadow_on_corp
      uses: ./actions/deploy_targets/                            
      with: 
        target_tuples: (corp-lca1, corp.shadow)
        code_version: $code_version
        config_version: $config_version
        auto_retry: $auto_retry
        auto_retry_success_rate: $auto_retry_success_rate
    - name: deploy_on_corp
      uses: ./actions/deploy_target/                            
      with: 
        target_tuple: (corp-lca1, corp.full)
        code_version: $code_version
        config_version: $config_version
        auto_retry: $auto_retry
        auto_retry_success_rate: $auto_retry_success_rate

  deploy_on_prod:
    needs: deploy_on_corp
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: canary_on_prod-ltx1
      uses: ./actions/deploy_target/                            
      with: 
        target_tuple: (prod-ltx1, prod.canary)
        code_version: $code_version
        config_version: $config_version
        distribution_percentage: 0.2
        auto_retry: $auto_retry
        auto_retry_success_rate: 1.0
    - name: promotion_on_prod-ltx1
      uses: ./actions/deploy_target/                            
      with: 
        target_tuple: (prod-ltx1, prod.full)
        code_version: $code_version
        config_version: $config_version
        distribution_percentage: 1.0
    - name: promotion_on_prods
      uses: ./actions/deploy_targets/                            
      with: 
        target_tuples: ((prod-lva1, prod.full), (prod-lor1, prod.full), (prod-lsg1, prod.full))        # This should be an array of tuple, GHA does not support array here though.
        code_version: $code_version
        config_version: $config_version
        auto_retry: $auto_retry
        auto_retry_success_rate: 0.9
    
